/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface MyDummyComponent {
    }
    interface MyNestedComponent {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyDummyComponentElement extends Components.MyDummyComponent, HTMLStencilElement {
    }
    var HTMLMyDummyComponentElement: {
        prototype: HTMLMyDummyComponentElement;
        new (): HTMLMyDummyComponentElement;
    };
    interface HTMLMyNestedComponentElement extends Components.MyNestedComponent, HTMLStencilElement {
    }
    var HTMLMyNestedComponentElement: {
        prototype: HTMLMyNestedComponentElement;
        new (): HTMLMyNestedComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-dummy-component": HTMLMyDummyComponentElement;
        "my-nested-component": HTMLMyNestedComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface MyDummyComponent {
    }
    interface MyNestedComponent {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-dummy-component": MyDummyComponent;
        "my-nested-component": MyNestedComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-dummy-component": LocalJSX.MyDummyComponent & JSXBase.HTMLAttributes<HTMLMyDummyComponentElement>;
            "my-nested-component": LocalJSX.MyNestedComponent & JSXBase.HTMLAttributes<HTMLMyNestedComponentElement>;
        }
    }
}
